### ISSUE TITLE
urlStream

### ISSUE THREAD

**Issue by ZeozinoJose32h** [sc4v3ng3r/anitube_crawler_api#1]
Obter a url para stream está quebrado? estou tentando obter a media "mediaplayback?expire=..." ao invés do "bg.mp4" sem sucesso até agora.

**Comment by sc4v3ng3r** [comment]
Se sua intenção for executar o vídeo, com o "bg.mp4" você consegue, porém você terá que mandar no seu header http o par "Referer" : "value". Dê uma olhada [aqui](https://github.com/sc4v3ng3r/animestore_app/blob/f4dd656257ccb7b3826d93f48a157449d52a2671/lib/logic/stores/video_player_store/VideoPlayerStore.dart#L86). Porém acredito que nem todos os episódios você vai consegui exibir desta forma. Faz um bom tempo que não observo as mudanças no site que crawler atua!
